apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpapp
  namespace: wpapp
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wpapp
        image: wordpress:6.2.1-apache
        resources:
          limits:
            memory: "1500Mi"
            cpu: "2000m"
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: password
          - name: WORDPRESS_DB_NAME
            value: wp
          - name: WORDPRESS_DB_HOST
            value: mysql-database-app-svc.database.svc.cluster.local
        volumeMounts:
          - name: wordpressdata
            mountPath: /var/www/html/
      volumes:
      - name: wordpressdata
        persistentVolumeClaim: 
          claimName: wpvol-pvc  