apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wpapp
  labels:
    app: wordpress
type: Opaque
data:
  user: YWRtaW4= # username data admin
  password: YWRtaW4xMjM= #pass admin123 using commain echo -n admin123 | openssl base64