kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort: 80
    NodePort: 31808