apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpvol 
  namespace: wpapp
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/wordpress
    server: 172.31.14.226

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpvol-pvc
  namespace: wpapp
  labels:
    app: wordpress 
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce