apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
spec:
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
      - name: gym-app
        image: prateekkumawat/app:gymweb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80