kind: Service
apiVersion: v1
metadata:
  name: web-service-img
spec:
  selector:
    app: web-service-img
  type: NodePort
  ports:
  - name: web-service-img-port
    nodePort: 31550
    port:  80
    targetPort:  80