apiVersion: v1
kind: Secret
metadata:
  name: mysql-database-app-secret
  namespace: database
  labels:
    app: mysql 
    enviornment: database
type: Opaque
data:
  user: admin # username data
  password: YWRtaW4xMjM= #pass admin123 using commain echo -n admin123 | openssl base64 