apiVersion: v1
kind: Service
metadata:
  name: mysql-database-app-svc
  namespace: database
  labels:
    app: mysql 
    enviornment: database
spec:
  selector:
    app: mysql 
    enviornment: database
  type: NodePort  
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31333
