apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    name: test1
spec:
  containers:
  - name: test1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
