apiVersion: v1
kind: PersistentVolume
metadata:
  name: datavol
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/cont1
    server: 172.31.14.226
