apiVersion: v1
kind: Secret
metadata:
  name: pgsql-database-app-secret
  namespace: postgres
  labels:
    app: pgsql 
    enviornment: database
type: Opaque
data:
  user: YWRtaW4= # username data admin
  password: YWRtaW4xMjM= #pass admin123 using commain echo -n admin123 | openssl base64 