kind: Service
apiVersion: v1
metadata:
  namespace: frontend
  name: uiapp-svc
  labels:
     app: node
     type: ui
spec:
  selector:
    app: node
  type: NodePort
  ports:
  - name: uiapp-port
    port: 3000
    targetPort: 3000
    nodePort: 31333